#!/bin/bash

echo "🚀 JARVIS 3D - Setup Guide"
echo "========================="
echo ""
echo "1. Install Dependencies"
echo "   npm install"
echo ""
echo "2. Configure Environment"
echo "   - Copy .env.example to .env.local"
echo "   - Get OpenAI API Key from: https://platform.openai.com/api-keys"
echo "   - Update OPENAI_API_KEY in .env.local"
echo ""
echo "3. Start Development Server"
echo "   npm run dev"
echo ""
echo "4. Open Browser"
echo "   http://localhost:3000"
echo ""
echo "✨ Features:"
echo "   ✅ 3D Holographic Scene"
echo "   ✅ AI Chat with OpenAI"
echo "   ✅ Real-time Streaming"
echo "   ✅ Neon Futuristic UI"
echo "   ✅ Glassmorphism Effects"
echo ""
